### ISSUE TITLE
Confusion about SPP params.

### ISSUE THREAD

**Issue by drcege** [hbilen/WSDDN#12]
I want to change the backbone network, e.g. resnet.  In SPP layer, there are two params, `offset1` and `offset2`. I can't figure out what they mean and how to calculate them. Where can I get more detailed explanation, any paper or blog? Thanks a lot.

**Comment by hbilen** [comment]
This is inspired from "spatial pyramid pooling in deep convolutional networks" paper. offset1 is related to offset in the receptive at the pooling layer because of the existing paddings and offset2 is just a shrinkage factor considering overestimated theoretical receptive field. You can use net.print function to see offset1. I didn't have time to tune these parameters, I am not sure how much it effects the detection performance.
